development:
  adapter: postgresql
  database: postgres
  password: 1111
  pool: 5
  timeout: 5000
  username: xxx
production:
  adapter: postgresql
  database: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
